<script setup lang="ts">
import { Form } from '@inlayphp/forms-vue'
import type { FormErrors, FormResource, FormTheme } from '@inlayphp/forms-vue'

type Enrollment = { secret: string; otpauthUri: string; recoveryCodes: string[] }
withDefaults(defineProps<{ status: { enabled: boolean }; enrollmentForm: FormResource; confirmForm: FormResource; regenerateForm?: FormResource | null; disableForm?: FormResource | null; enrollment?: Enrollment | null; enrollmentQrCode?: string | null; recoveryCodes?: string[] | null; errors?: FormErrors; flash?: { success?: string | null }; theme?: FormTheme; className?: string }>(), { errors: () => ({}), theme: () => ({}), className: '' })
</script>

<template>
  <main :class="`mx-auto w-full max-w-3xl text-(--inlay-foreground) antialiased ${className}`.trim()" data-slot="two-factor-settings">
    <header><p class="text-sm font-semibold tracking-wide text-(--inlay-accent) uppercase">Security</p><h1 class="mt-2 text-3xl font-semibold tracking-tight">Two-factor authentication</h1><p class="mt-3 max-w-2xl text-sm leading-6 text-(--inlay-muted)">Protect this panel with an authenticator app and one-use recovery codes.</p></header>
    <div v-if="flash?.success" class="mt-6 rounded-(--inlay-radius) border border-(--inlay-success)/25 bg-(--inlay-success-surface) px-4 py-3 text-sm text-(--inlay-success)" role="status">{{ flash.success }}</div>
    <section class="mt-7 rounded-(--inlay-radius) border border-(--inlay-border) bg-(--inlay-surface) p-6 shadow-sm"><div class="flex items-start justify-between gap-4"><div><h2 class="text-lg font-semibold">Authenticator app</h2><p class="mt-1 text-sm text-(--inlay-muted)">{{ status.enabled ? 'Your account requires a code at sign-in.' : 'Add an authenticator app to require a code at sign-in.' }}</p></div><span class="rounded-full px-3 py-1 text-xs font-semibold" :data-state="status.enabled ? 'enabled' : 'disabled'">{{ status.enabled ? 'Enabled' : 'Not enabled' }}</span></div>
      <div v-if="!status.enabled && !enrollment" class="mt-6"><Form :errors="errors" :resource="enrollmentForm" :theme="theme" /></div>
      <div v-if="enrollment" class="mt-6 grid gap-5"><div class="rounded-lg border border-(--inlay-border) bg-(--inlay-surface-muted) p-4"><p class="text-sm font-semibold">1. Add this account to your authenticator</p><img v-if="enrollmentQrCode" :src="enrollmentQrCode" alt="Authenticator setup QR code" class="mt-4 size-48 rounded-lg bg-white p-2"><p class="mt-2 break-all font-mono text-xs text-(--inlay-muted)">{{ enrollment.otpauthUri }}</p><p class="mt-2 text-xs text-(--inlay-muted)">{{ enrollmentQrCode ? 'Scan the QR code, or enter the setup URI manually.' : 'Use the URI with a QR-code component supplied by your application.' }}</p></div><div><p class="mb-3 text-sm font-semibold">2. Confirm with the six-digit code</p><Form :errors="errors" :resource="confirmForm" :theme="theme" /></div><div class="rounded-lg border border-(--inlay-warning)/25 bg-(--inlay-warning-surface) p-4 text-sm text-(--inlay-warning)"><p class="font-semibold">Save your recovery codes</p><p class="mt-1">Each code can be used once if you lose access to your authenticator.</p><code class="mt-3 grid grid-cols-2 gap-2 font-mono text-xs"><span v-for="code in enrollment.recoveryCodes" :key="code">{{ code }}</span></code></div></div>
    </section>
    <section v-if="status.enabled && !enrollment" class="mt-6 grid gap-6"><div class="rounded-(--inlay-radius) border border-(--inlay-border) bg-(--inlay-surface) p-6"><h2 class="font-semibold">Recovery codes</h2><p class="mt-1 mb-5 text-sm text-(--inlay-muted)">Regenerating invalidates all previous codes.</p><Form :errors="errors" :resource="regenerateForm!" :theme="theme" /></div><div class="rounded-(--inlay-radius) border border-(--inlay-danger)/25 bg-(--inlay-surface) p-6"><h2 class="font-semibold text-(--inlay-danger)">Disable two-factor authentication</h2><p class="mt-1 mb-5 text-sm text-(--inlay-muted)">You will no longer be asked for a code at sign-in.</p><Form :errors="errors" :resource="disableForm!" :theme="theme" /></div></section>
    <section v-if="recoveryCodes?.length" class="mt-6 rounded-(--inlay-radius) border border-(--inlay-warning)/25 bg-(--inlay-warning-surface) p-6 text-(--inlay-warning)"><h2 class="font-semibold">New recovery codes</h2><p class="mt-1 text-sm">These replace every previous recovery code. Save them now.</p><code class="mt-4 grid grid-cols-2 gap-2 font-mono text-xs"><span v-for="code in recoveryCodes" :key="code">{{ code }}</span></code></section>
  </main>
</template>
